python -m dlmcsp.scripts.sample_disc_remask \
  --data /home/jmmu/dlmcsp/dlmcsp/data/mp_20/test.clean.ms.jsonl \
  --vocab /home/jmmu/dlmcsp/configs/vocab.yaml \
  --ckpt /home/jmmu/dlmcsp/dlmcsp/ckpts/llada_cont.best.pt \
  --out  /home/jmmu/dlmcsp/dlmcsp/outputs/test.disc.pred.jsonl \
  --decode_out /home/jmmu/dlmcsp/dlmcsp/outputs/test.disc.ms_pred.decoded.jsonl \
  --batch 256 \
  --steps 30 \
  --temp_init 1.5 --temp_final 0.5 \
  --gumbel_scale 0.3 \
  --schedule cosine \
  --r_init 1.0 --r_final 0.1 --gamma 1.5